In [1]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd

In [2]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [3]:
a = np.arange(9).reshape(3,3)

In [4]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([a,a],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([a,a])


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser= Series(list('123'), index=list('XYZ'))

In [8]:
ser

X    1
Y    2
Z    3
dtype: object

In [9]:
ser2= Series(list('12'),index=['1','2'])

In [10]:
ser2

1    1
2    2
dtype: object

In [12]:
pd.concat([ser,ser2],axis=1)

0    1
1  NaN    1
2  NaN    2
X    1  NaN
Y    2  NaN
Z    3  NaN

In [13]:
pd.concat([ser,ser2],keys= ['cat1','cat2'])

cat1  X    1
      Y    2
      Z    3
cat2  1    1
      2    2
dtype: object

In [14]:


#Lastly, everything works similarly in DataFrames

dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])

dframe1

X         Y         Z
0 -0.202795 -0.503763 -0.764067
1 -0.095063 -0.043544 -1.272600
2  0.757614 -1.927794  1.288788
3  0.616069 -0.505023  0.283966

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -0.202795 -0.503763 -0.764067
1       NaN -0.095063 -0.043544 -1.272600
2       NaN  0.757614 -1.927794  1.288788
3       NaN  0.616069 -0.505023  0.283966
0  0.233609 -1.072296  0.410837       NaN
1 -0.209882 -1.100723  0.166004       NaN
2 -0.633191  0.062462 -0.617380       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -0.202795 -0.503763 -0.764067
1       NaN -0.095063 -0.043544 -1.272600
2       NaN  0.757614 -1.927794  1.288788
3       NaN  0.616069 -0.505023  0.283966
4  0.233609 -1.072296  0.410837       NaN
5 -0.209882 -1.100723  0.166004       NaN
6 -0.633191  0.062462 -0.617380       NaN

In [17]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
           index=['Q','R','S','T','U','V'])

#Second Series (based off length of ser1)
ser2 = Series(np.arange(len(ser1), dtype=np.float64),
           index=['Q','R','S','T','U','V'])

ser2[-1] = np.nan

In [18]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    NaN
dtype: float64

In [19]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    NaN
dtype: float64

In [20]:
#Lets make some 
dframe_odds = DataFrame({'X': [1., np.nan, 3., np.nan],
                     'Y': [np.nan, 5., np.nan, 7.],
                     'Z': [np.nan, 9., np.nan, 11.]})
dframe_evens = DataFrame({'X': [2., 4., np.nan, 6., 8.],
                     'Y': [np.nan, 10., 12., 14., 16.]})

dframe_odds

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [21]:
dframe_evens

X     Y
0  2.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [22]:
dframe_odds.combine_first(dframe_evens)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

##Reshape

In [24]:

# Create DataFrame
dframe1 = DataFrame(np.arange(8).reshape((2, 4)),
                 index=pd.Index(['LA', 'SF'], name='city'),
                 columns=pd.Index(['A', 'B', 'C','D'], name='letter'))
#Show
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [26]:
df= dframe1.stack()
df

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int64

In [30]:
df.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [31]:
df.unstack('letter')

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [32]:
df.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [33]:
s= Series([0,1,2],index=list('ABC'))
x=Series([4,7,5], index=list('QAB'))
s

A    0
B    1
C    2
dtype: int64

In [34]:
x

Q    4
A    7
B    5
dtype: int64

In [35]:
dframe= pd.concat([s,x],keys=['okay','bye'])

In [36]:
dframe

okay  A    0
      B    1
      C    2
bye   Q    4
      A    7
      B    5
dtype: int64

In [37]:
dframe.unstack()

A    B    C    Q
okay  0.0  1.0  2.0  NaN
bye   7.0  5.0  NaN  4.0

In [38]:
dframe.unstack().stack()

okay  A    0.0
      B    1.0
      C    2.0
bye   A    7.0
      B    5.0
      Q    4.0
dtype: float64

In [39]:
 dframe.unstack()

A    B    C    Q
okay  0.0  1.0  2.0  NaN
bye   7.0  5.0  NaN  4.0

In [ ]:
 dframe.unstack().stack()