In [1]:
import numpy as np

In [4]:
my_list=[1,2,3]

In [5]:
 my_array= np.array(my_list)

In [6]:
my_array

array([1, 2, 3])

In [7]:
my_list2=[21,31,41]

In [9]:
my_lists=[my_list,my_list2]

In [10]:
my_arrays=np.array(my_lists)

In [11]:
my_arrays

array([[ 1,  2,  3],
       [21, 31, 41]])

In [12]:
my_arrays.dtype

dtype('int64')

In [13]:
my_arrays.shape

(2, 3)

In [14]:
 np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])

In [15]:
zero=np.zeros(5)

In [16]:
zero

array([ 0.,  0.,  0.,  0.,  0.])

In [17]:
zero.dtype


dtype('float64')

In [18]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
okay=np.ones([4,4])

In [20]:
okay

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [22]:
np.arange(10,30,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])