In [1]:
import numpy as np

In [5]:
from __future__ import division

In [6]:
5/2

2.5

In [7]:
arr=np.arange(3,11)

In [8]:
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
arr[2:5]=100

In [10]:
arr

array([  3,   4, 100, 100, 100,   8,   9,  10])

In [12]:
arr_copy=arr.copy()

In [13]:
arr_copy

array([  3,   4, 100, 100, 100,   8,   9,  10])

In [15]:
arr_2D=([1,2,3],[4,5,6],[100,99,92])
arr_2D


([1, 2, 3], [4, 5, 6], [100, 99, 92])

In [22]:
arr_2D[:2][1:]

([4, 5, 6],)

In [27]:
arr_2D[2:8][:]

([100, 99, 92],)

In [34]:
a=np.ones((10,10))

In [35]:
a

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [41]:
for i in range(a.shape[1]):
    a[i]=i

In [42]:
a

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

####Transportation

In [43]:
new=np.arange(1,51).reshape(10,5)

In [44]:
new

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [45]:
new.T


array([[ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49],
       [ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50]])

In [46]:
np.dot(new.T,new)

array([[7585, 7820, 8055, 8290, 8525],
       [7820, 8065, 8310, 8555, 8800],
       [8055, 8310, 8565, 8820, 9075],
       [8290, 8555, 8820, 9085, 9350],
       [8525, 8800, 9075, 9350, 9625]])

In [55]:
okay=np.array([[1,2,3],[4,5,6]])
okay

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
okay.swapaxes(0,1)

array([[1, 4],
       [2, 5],
       [3, 6]])