In [1]:
import numpy as np

In [5]:
arr=np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [6]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [7]:
np.exp(arr)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [9]:
website='https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html'
import webbrowser
webbrowser.open(website)

True